### ISSUE TITLE
Massive lag when right clicking to prioritize something.

### ISSUE THREAD

**Issue by TheKarixPL** [juanosarg/VanillaIdeologyExpanded-Memes#1]
Hello.

I discovered that method "bool AppliesToPawn(Pawn p, out string reason, LordJob_Ritual ritual = null, RitualRoleAssignments assignments = null, Precept_Ritual precept = null, bool skipReason = false)" in class VanillaMemesExpanded.RitualRole_BestMelee produces massive lag when right clicking on something. As I discovered block:

foreach (Pawn pawn in PawnsFinder.AllMapsCaravansAndTravelingTransportPods_Alive_FreeColonists)
			{
				if (pawn.skills.GetSkill(SkillDefOf.Melee).Level > highestSkillLevel)
				{
					highestSkillLevel = pawn.skills.GetSkill(SkillDefOf.Melee).Level;
					mostSkilledPawn = pawn;
				}
			}
consumes 3k to 5k cpu cycles and repeats 1k times per second.
When I disabled this method by adding at the begining of method "return false;", lag disappeared.

**Comment by juanosarg** [comment]
I haven't seen it peak above 10 ms, which, yeah, it's laggy, but not enough to be massive lag by a long shot.

I will modify the class to cache the data in a static class
