### ISSUE TITLE
The static tracker_backup dictionaries can get loaded as null

### ISSUE THREAD

**Issue by nearbear** [juanosarg/VanillaIdeologyExpanded-Memes#7]
I've had this error in a couple of places but I fixed some of them by initializing the backup dictionaries to an empty one if the scribe lookup set the backup map to null. Here is my save file information related to the alcohol tracker:

			<li Class="VanillaMemesExpanded.GameComponent_AlcoholScarsAndSlaveryTracker">
				<tickCounterBoozeAndScars>12900</tickCounterBoozeAndScars>
				<colonist_booze_tracker_backup IsNull="True" />
				<colonist_scar_counter_backup IsNull="True" />
				<enslavedPawns_backup />
			</li>

This eventually leads to a repeating null pointer error that usually doesn't cause any problems, but in one instance it prevented me from forming caravans.

My dnSpy fix for the caravan tracker (not sure if this is the best way but it worked for me):

		public override void ExposeData()
		{
			base.ExposeData();
			Scribe_Values.Look<int>(ref this.tickCounter, "tickCounterTravel", 0, true);
			Scribe_Values.Look<int>(ref this.ticksWithoutAbandoningbackup, "ticksWithoutAbandoningbackup", 0, true);
			Scribe_Collections.Look<Pawn, int>(ref this.colonist_caravan_tracker_backup, "colonist_caravan_tracker_backup", LookMode.Reference, LookMode.Value, ref this.list2, ref this.list3, true);
	+		if (this.colonist_caravan_tracker_backup == null)
	+		{
	+			this.colonist_caravan_tracker_backup = new Dictionary<Pawn, int>();
	+		}
			Scribe_Values.Look<int>(ref this.ticksWithoutTradingbackup, "ticksWithoutTradingbackup", 0, true);
		}

and my alcohol thought stack trace:

    Exception while recalculating VME_Alcohol_Demanded thought state for pawn Toxlerchama: System.NullReferenceException: Object reference not set to an instance of an object
      at VanillaMemesExpanded.ThoughtWorker_Precept_Alcohol.ShouldHaveThought (Verse.Pawn p) [0x00001] in <ae6e7310399845e0a7726c36df5d2aa5>:0 
      at RimWorld.ThoughtWorker_Precept.CurrentStateInternal (Verse.Pawn p) [0x00054] in <f4c3e52a3fec4807a874d50b5e1c361f>:0 
      at RimWorld.ThoughtWorker.CurrentState (Verse.Pawn p) [0x00010] in <f4c3e52a3fec4807a874d50b5e1c361f>:0 
      at (wrapper dynamic-method) RimWorld.SituationalThoughtHandler.RimWorld.SituationalThoughtHandler.TryCreateThought_Patch0(RimWorld.SituationalThoughtHandler,RimWorld.ThoughtDef)
    UnityEngine.StackTraceUtility:ExtractStackTrace ()
    (wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
    (wrapper dynamic-method) RimWorld.SituationalThoughtHandler:RimWorld.SituationalThoughtHandler.TryCreateThought_Patch0 (RimWorld.SituationalThoughtHandler,RimWorld.ThoughtDef)
    RimWorld.SituationalThoughtHandler:CheckRecalculateMoodThoughts ()
    RimWorld.SituationalThoughtHandler:AppendMoodThoughts (System.Collections.Generic.List`1<RimWorld.Thought>)
    RimWorld.ThoughtHandler:GetAllMoodThoughts (System.Collections.Generic.List`1<RimWorld.Thought>)
    RimWorld.ThoughtHandler:GetDistinctMoodThoughtGroups (System.Collections.Generic.List`1<RimWorld.Thought>)
    (wrapper dynamic-method) RimWorld.ThoughtHandler:RimWorld.ThoughtHandler.TotalMoodOffset_Patch2 (RimWorld.ThoughtHandler)
    RimWorld.Need_Mood:get_CurInstantLevel ()
    RimWorld.Need_Seeker:NeedInterval ()
    RimWorld.Need_Mood:NeedInterval ()
    RimWorld.Pawn_NeedsTracker:NeedsTrackerTick ()
    (wrapper dynamic-method) Verse.Pawn:Verse.Pawn.Tick_Patch2 (Verse.Pawn)
    (wrapper dynamic-method) Verse.TickList:Verse.TickList.Tick_Patch0 (Verse.TickList)
    (wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch7 (Verse.TickManager)
    Verse.TickManager:TickManagerUpdate ()
    (wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch0 (Verse.Game)
    (wrapper dynamic-method) Verse.Root_Play:Verse.Root_Play.Update_Patch0 (Verse.Root_Play)

**Comment by legodude17** [comment]
Please use [Vanilla-Expanded/VanillaIdeologyExpanded-Memes](https://github.com/Vanilla-Expanded/VanillaIdeologyExpanded-Memes) instead.
